# Generated by Django 5.1.2 on 2024-11-08 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aviso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.IntegerField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('Id_Aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aviso.aviso')),
            ],
        ),
    ]
