# Generated by Django 5.1.2 on 2024-11-08 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clasificacion', '0001_initial'),
        ('Cliente', '0001_initial'),
        ('Sede', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.IntegerField()),
                ('Id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('Id_Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Id_MetodoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clasificacion.metodopago')),
                ('Id_Sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sede.sede')),
            ],
        ),
    ]
