# Generated by Django 5.1.2 on 2024-11-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clasificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
